### ISSUE TITLE
Slow load times for extras

### ISSUE THREAD

**Issue by Kacarott** [codewars/factor#11]
In 0.99, some commonly used vocabularies in `extras` now take a considerable amount of time to load. For example simply loading `sequences.extras` [adds 5-6 *seconds* to the runtime](https://www.codewars.com/kumite/65b66728df6c390f182aa83f?sel=65b66728df6c390f182aa83f).

Commonly used vocabs from `extras` should be preloaded so that load times do not affect code runtime.

**Comment by nomennescio** [comment]
I wouldn't label this a bug; extras was not preloaded in 0.98, and also not in 0.99.
I understand your argument that some vocabs in extras deserve to be promoted to being preloaded.
Good idea, but will do that in `testest`.

**Comment by Kacarott** [comment]
It is definitely a bug, because it makes extras unusable for performance kata in 0.99. In 0.98 it took only about 1 second to load `sequences.extras`, in 0.99 it takes 5-6 seconds.

It should be done here, as this is has nothing to do with `testest`. See #13

**Comment by nomennescio** [comment]
See #13, I will address this in `testest`
