### ISSUE TITLE
Do not install imager.factor as a vocabulary

### ISSUE THREAD

**Issue by Kacarott** [codewars/factor#14]
`imager.factor` is currently installed as a full vocabulary before being run during the docker build process, and is never removed. It is not required, or ever used after the build process, and so there is no reason for it to be installed as a vocabulary.

Instead, it should be run as a one-time script instead of being installed as a vocabulary. This will save some (trivial amount) of memory, simplify the build process, and prevent from polluting the vocabulary namespace.

**Comment by nomennescio** [comment]
See #13

Polluting the vocabulary namespace is of no concern, as nameclashes will be caught before releases, but I consider those extremely unlikely.
